// Auto-generated file
// DO NOT EDIT THIS FILE MANUALLY

export type MongoDBCollections = 
  | 'admins'
  | 'attendances'
  | 'attendanceuploads'
  | 'audits'
  | 'banks'
  | 'billinginvoices'
  | 'billingworkorderitems'
  | 'billingworkorders'
  | 'chalans'
  | 'checklists'
  | 'chemicalissueandreplacementregisters'
  | 'chemicalissues'
  | 'chemicalpurchases'
  | 'chemicals'
  | 'compliances'
  | 'consumables'
  | 'correctiveandpreventives'
  | 'dailyutilisations'
  | 'departmenthrs'
  | 'departments'
  | 'designations'
  | 'documents'
  | 'employeedatas'
  | 'employees'
  | 'engineers'
  | 'enterprises'
  | 'esilocations'
  | 'fuelmanagements'
  | 'fuels'
  | 'housekeepingaudits'
  | 'invoices'
  | 'items'
  | 'logs'
  | 'monthlytasks'
  | 'ppeissueandreplacements'
  | 'ppeissues'
  | 'ppepurchases'
  | 'ppes'
  | 'questions'
  | 'safetyindandtrainings'
  | 'safetytoolissues'
  | 'safetytoolmaintenances'
  | 'safetytoolpurchases'
  | 'safetytools'
  | 'sites'
  | 'sitesecurityuploads'
  | 'siteuploads'
  | 'stores'
  | 'stripuploads'
  | 'tests'
  | 'toolaudits'
  | 'toolboxtalks'
  | 'toolcheckings'
  | 'toolchecklists'
  | 'toolgroups'
  | 'toolissueandreplacementregisters'
  | 'toolissues'
  | 'toolmaintanences'
  | 'tools'
  | 'toolsubgroups'
  | 'trainingexamattempts'
  | 'trainingexams'
  | 'trainings'
  | 'users'
  | 'vehicles'
  | 'wages'
  | 'workorderhrs'
  | 'workorders';

export const collectionValues = [
  'admins',
  'attendances',
  'attendanceuploads',
  'audits',
  'banks',
  'billinginvoices',
  'billingworkorderitems',
  'billingworkorders',
  'chalans',
  'checklists',
  'chemicalissueandreplacementregisters',
  'chemicalissues',
  'chemicalpurchases',
  'chemicals',
  'compliances',
  'consumables',
  'correctiveandpreventives',
  'dailyutilisations',
  'departmenthrs',
  'departments',
  'designations',
  'documents',
  'employeedatas',
  'employees',
  'engineers',
  'enterprises',
  'esilocations',
  'fuelmanagements',
  'fuels',
  'housekeepingaudits',
  'invoices',
  'items',
  'logs',
  'monthlytasks',
  'ppeissueandreplacements',
  'ppeissues',
  'ppepurchases',
  'ppes',
  'questions',
  'safetyindandtrainings',
  'safetytoolissues',
  'safetytoolmaintenances',
  'safetytoolpurchases',
  'safetytools',
  'sites',
  'sitesecurityuploads',
  'siteuploads',
  'stores',
  'stripuploads',
  'tests',
  'toolaudits',
  'toolboxtalks',
  'toolcheckings',
  'toolchecklists',
  'toolgroups',
  'toolissueandreplacementregisters',
  'toolissues',
  'toolmaintanences',
  'tools',
  'toolsubgroups',
  'trainingexamattempts',
  'trainingexams',
  'trainings',
  'users',
  'vehicles',
  'wages',
  'workorderhrs',
  'workorders'
] as const;

export type CollectionValues = typeof collectionValues[number];
